services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp
      - 8388:8388/udp
      - 8087:8080
      - 6881:6881/tcp
      - 6881:6881/udp
      - 9117:9117
    volumes:
      - ./gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=i3yFgAwLnL1L2BKznE7ZDsXd
      - OPENVPN_PASSWORD=f2zD2yGfKfxz4eba5z46iT39
      - SERVER_COUNTRIES=Switzerland
      
  qbittorrent:
    image: wernight/qbittorrent
    restart: unless-stopped
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $DOCKERDIR/qbittorrent/config:/config
      - $DOCKERDIR/qbittorrent/torrents:/torrents
      - $DOCKERDIR/qbittorrent/plugins:/plugins
      - /mnt/media/Downloads:/downloads
    network_mode: service:gluetun
    user: "1000:1000"
    depends_on: 
      jackett:
        condition: service_started
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=true
    volumes:
      - $DOCKERDIR/jackett/data:/config
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_started
            
  web-browser:
    image: hurlenko/filebrowser
    container_name: webrowser
##    user: "server:server"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media:/data
    ports:
      - 8089:8080
    restart: unless-stopped
